trigger:
  branches:
    include:
      - master
pr:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: test-all-debug.yml
    variables:
      TOOLCHAIN: 1.46.0

  - job: macOS
    pool:
      vmImage: macos-10.14
    steps:
      - template: test-all-debug.yml
    variables:
      TOOLCHAIN: 1.46.0

  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - script: choco install -y ninja
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8.4"
          addToPath: true
          architecture: "x64"
      - template: test-all-debug.yml
    variables:
      TOOLCHAIN: 1.46.0
